### ISSUE TITLE
WHATS WRONG?

### ISSUE THREAD

**Issue by sitxxar** [maldiharyojudanto/yescoinwhite-bot#1]
![image](https://github.com/maldiharyojudanto/yescoinwhite-bot/assets/37711440/10281fe5-47c0-4543-b0d2-a736f6441015)

**Comment by maldiharyojudanto** [comment]
> ![image](https://private-user-images.githubusercontent.com/37711440/341282985-10281fe5-47c0-4543-b0d2-a736f6441015.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg4NjIyNjksIm5iZiI6MTcxODg2MTk2OSwicGF0aCI6Ii8zNzcxMTQ0MC8zNDEyODI5ODUtMTAyODFmZTUtNDdjMC00NTQzLWIwZDItYTczNmY2NDQxMDE1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjIwVDA1MzkyOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk2ZWYzMWE5ZWI0YTBhNjBlOGNjN2E2ZWU2MjA5MzYwYzc4ZTRkNDI3NWJmYzg3OTIxNTA0NGI1MGYxZGMwYTImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.F_vXbRt_pvpb6CebBP1Z3Ef2z6ykPUTEaQ8aw15Jy-g)

remove line 364 if you not using Windows, save and run again
